apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.groupSync.namespace }}
  labels:
    {{- include "group-sync-operator-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
---

