{{- if .Values.oauthSecretExtraction.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.oauthSecretExtraction.serviceAccount.name }}
  namespace: {{ .Values.groupSync.namespace }}
  labels:
    {{- include "group-sync-operator-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth-secret-extraction
  annotations:
    argocd.argoproj.io/sync-wave: "1"
automountServiceAccountToken: true
{{- end }}

