apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group-sync-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift-requirement: "true"
    openshift-version: "4.x"
spec:
  project: default
  source:
    repoURL: https://ephico2real2.github.io/group-sync-operator-helm-chart
    targetRevision: HEAD
    chart: group-sync-operator-helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: group-sync-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

