---
# Source: group-sync-chart/templates/groupsync.yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "0/30 * * * *"
  providers:
    - name: ldap-git-ocp
      ldap:
        url: "ldaps://ldap.ephicoreal2.net:636"
        insecure: false
        prune: true
        ca:
          kind: ConfigMap
          name: ca-config-map
          key: ca.crt
          namespace: openshift-config
        credentialsSecret:
          kind: Secret
          name: ldap-group-sync
          namespace: group-sync-operator
        rfc2307:
          usersQuery:
            baseDN: "o=ephicoreal2"
            derefAliases: "never"
            pageSize: 0
            scope: "sub"
            timeout: 0

          groupsQuery:
            baseDN: "ou=Groups,o=ephicoreal2"
            derefAliases: "never"
            filter: "(&(objectClass=groupOfNames)(cn=app-git-*))"
            pageSize: 0
            scope: "sub"
            timeout: 0

          groupNameAttributes:
            - cn
          groupUIDAttribute: dn
          groupMembershipAttributes:
            - member
          userNameAttributes:
            - uid
          userUIDAttribute: dn
          tolerateMemberNotFoundErrors: true
          tolerateMemberOutOfScopeErrors: true
---
# Source: group-sync-chart/templates/operator-group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: group-sync-operator-group
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    olm.providedAPIs: GroupSync.v1alpha1.redhatcop.redhat.io
spec:
  targetNamespaces:
    - group-sync-operator
  upgradeStrategy: Default
---
# Source: group-sync-chart/templates/operator-subscription.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: alpha
  config:
    env:
      - name: WATCH_NAMESPACE
        value: "group-sync-operator,openshift-config"
  installPlanApproval: Automatic
  name: ldap-group-sync
  source: community-operators
  sourceNamespace: openshift-marketplace
