name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - '.github/workflows/lint-test.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.pull_request.base.ref }}

      # Optional: Add chart-testing (install) if you have a test environment
      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.5.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Run chart-testing (install)
      #   run: ct install --target-branch ${{ github.event.pull_request.base.ref }}
