{{- if .Values.groupSync.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: {{ .Values.groupSync.name }}
  namespace: {{ .Values.groupSync.namespace }}
  labels:
    {{- include "group-sync-operator-helm.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  schedule: {{ .Values.groupSync.schedule | quote }}
  providers:
    - name: {{ .Values.groupSync.providerName }}
      ldap:
        url: {{ .Values.groupSync.url | quote }}
        insecure: {{ .Values.groupSync.insecure | default false }}
        prune: true
        {{- if not .Values.groupSync.insecure }}
        ca:
          kind: ConfigMap
          name: {{ .Values.groupSync.ca.name }}
          key: {{ .Values.groupSync.ca.key }}
          namespace: {{ .Values.groupSync.ca.namespace }}
        {{- end }}
        credentialsSecret:
          kind: Secret
          name: {{ .Values.groupSync.credentialsSecret.name }}
          namespace: {{ .Values.groupSync.credentialsSecret.namespace }}
        rfc2307:
          usersQuery:
            baseDN: {{ .Values.groupSync.rfc2307.usersQuery.baseDN | quote }}
            derefAliases: {{ .Values.groupSync.rfc2307.usersQuery.derefAliases | quote }}
            {{- if .Values.groupSync.rfc2307.usersQuery.filter }}
            filter: {{ .Values.groupSync.rfc2307.usersQuery.filter | quote }}
            {{- end }}
            pageSize: {{ .Values.groupSync.rfc2307.usersQuery.pageSize }}
            scope: {{ .Values.groupSync.rfc2307.usersQuery.scope | quote }}
            timeout: {{ .Values.groupSync.rfc2307.usersQuery.timeout }}

          groupsQuery:
            baseDN: {{ .Values.groupSync.rfc2307.groupsQuery.baseDN | quote }}
            derefAliases: {{ .Values.groupSync.rfc2307.groupsQuery.derefAliases | quote }}
            filter: {{ .Values.groupSync.rfc2307.groupsQuery.filter | quote }}
            pageSize: {{ .Values.groupSync.rfc2307.groupsQuery.pageSize }}
            scope: {{ .Values.groupSync.rfc2307.groupsQuery.scope | quote }}
            timeout: {{ .Values.groupSync.rfc2307.groupsQuery.timeout }}

          groupNameAttributes:
            - cn
          groupUIDAttribute: dn
          groupMembershipAttributes:
            - member
          userNameAttributes:
            - uid
          userUIDAttribute: dn
          tolerateMemberNotFoundErrors: true
          tolerateMemberOutOfScopeErrors: true
{{- end }}
